config/routes.rb
Smithsongs::Application.routes.draw do

  resources :orders

  resources :line_items

  resources :carts

  resources :products

  resources :events

  resources :venues

  resources :sessions

  root to: 'static_pages#home'
  
  match '/home', to: 'static_pages#home'
  match '/about', to: 'static_pages#about'
  match '/photos', to: 'static_pages#photos'
  match '/videos', to: 'static_pages#videos'
  match '/album', to: 'static_pages#album'
  match '/store', to: 'store#index'
  match '/cart', to: 'carts#show'
  match '/login', to: 'sessions#new'
  match '/logout', to: 'sessions#destroy'
  
  

end

app/views/layouts/_currentEvents.html.erb
<div class="latest_news_module">
  <div id="title">
    <p>Where's Steve?</p>
  </div>
  <div id="latest_news_items">

    <% @current_events.each do |event| %>
    <div class="latest_news_item scrollEl">
      <a href="<%= event_path(event.id) %>">
        <div class="news_square_date">
          <div class="square_month"><%= event.event_date.strftime("%b") %></div>
          <div class="square_day"><%= event.event_date.strftime("%d") %></div>
        </div>
        <span class="latest_news_title"><%= event.title %></span>
      </a>
    </div>
    <% end %>

  </div>
</div>

app/views/layouts/_music_player.html.erb
  <div id="music" data-music="<%= @music_list.to_json %>"></div>
  <div id="jquery_jplayer_1" class="jp-jplayer"></div>
  <div id="jp_container_1" class="jp-audio">
    <%= image_tag "logo.jpg" %>
    <div class="jp-type-playlist">
      <div class="jp-gui jp-interface">
        <div class="jp-times">
          <div class="jp-current-time"></div>
          <div class="jp-duration"></div>
        </div>
        <div class="jp-control-box">
          <ul class="jp-controls">
            <li><a href="javascript:;" class="jp-previous" tabindex="1">previous</a></li>
            <li><a href="javascript:;" class="jp-play" tabindex="1">play</a></li>
            <li><a href="javascript:;" class="jp-pause" tabindex="1">pause</a></li>
            <li><a href="javascript:;" class="jp-next" tabindex="1">next</a></li>
          </ul>
          <div class="jp-progress">
            <div class="jp-seek-bar">
              <div class="jp-play-bar"></div>
            </div>
          </div>
        </div>
        <div class="jp-playlist">
          <ul>
            <li></li>
          </ul>
        </div> 
      </div>
      <div class="jp-no-solution">
        <span>Update Required</span>
          To play the media you will need to either update your browser to a recent version or update your 
          <a href="http://get.adobe.com/flashplayer/" target="_blank">Flash plugin</a>.
      </div>
    </div>
  </div> 

app/views/layouts/_navigation.html.erb
<nav>
  <span id='for_height'>A</span>
  <ul>
    <li><%= link_to 'Home', '/home', :id => 'Home' %></li>
    <li><%= link_to 'About', '/about', :id => 'About' %></li>
    <li><%= link_to 'Photos', '/photos', :id => 'Photos' %></li>
    <li><%= link_to 'Videos', '/videos', :id => 'Videos' %></li>
    <li><%= link_to 'Calendar', events_path, :id => 'Events' %></li>
    <li><%= link_to 'Start Today', '/album', :id => 'Album' %></li>
    <% if admin? %>
      <li><%= link_to 'Venues', venues_path, :id => 'Venues' %></li>
      <li><%= link_to 'New Event', new_event_path, :id => 'NewEvent' %></li>
    <% end %>
  </ul>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-Language" content="en" />
  <meta name="description" content="Steve Smith is a Midwestern singer/songwriter/guitar man that plays hundreds of shows a year. Steve Smith is an Indianapolis based musician.">
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    "jplayer.pink.flag", :media => "all" %>
  <%= stylesheet_link_tag    "smoothDivScroll", :media => "all" %>
 
  <%= stylesheet_link_tag    "photobox", :media => "all" %>
  <%= stylesheet_link_tag    "photobox.ie", :media => "all" %>
  <%= javascript_include_tag "https://js.stripe.com/v1/" %>
  <%= javascript_include_tag "application", "jquery.jplayer.min", "jplayer.playlist.min", "mbScrollable.js", "jquery.backgroundSize.js" %>
  <%= javascript_include_tag "https://maps.googleapis.com/maps/api/js?key=AIzaSyAk9XtINmxyf6Rnvwe_ynWuR9-VR4XSAaE&sensor=false" %>
  <%= javascript_include_tag "jquery-ui-1.8.23.custom.min.js", "jquery.kinetic.js", "jquery.mousewheel.min.js", "smooth-div-scroll-edit.min.js", "photobox.min.js" %>
  <%= stylesheet_link_tag "https://fonts.googleapis.com/css?family=Droid+Sans|Lobster" %>
  <%= csrf_meta_tags %>
  <%= tag :meta, :name => "stripe-key", :content => STRIPE_PUBLIC_KEY %>
</head>

<body>

  <%= render "layouts/music_player" %>
  <%= render "layouts/navigation" %>

  <div id="container">
    <div id="sidebar">
      <%= render "layouts/currentEvents" %>
    </div>
    <div id="main">
      <div id="page" data-pjax-container>
        <%= yield %>
      </div>
    </div>
  </div>
  
</body>
</html>